print(3+3)
print(3-3)
print(3*3)
print(3%5)
print(3/5)
print(3**3) # Exponet
print(3//5) #Flooring division - Return whats infront of the num
print()
print("My name is Liban Joe Luis Britt")
print('My family name is Britt')
print('I live in America')
print('My goal is to learn python and do something impactful with my learnings')
print()
print(type(19))
print(type(9.9))
print(type(3.14))
print(type(4-4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type('My name is Liban'))
print(type(None))